
version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: inventory
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    restart: always
    environment:
      - DB_HOST=localhost
      - DB_USER=root
      - DB_PASSWORD=Pincha11
      - DB_NAME=challenge
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app