client_config_backend: settings
client_config:
  client_id: #insertar client_id que se encuentra en el archivo client_secrets.json
  client_secret: #insertar el client_secret que se encuentra en el archivo client_secrets.json

save_credentials: True
save_credentials_backend: file
save_credentials_file: ./files/credentials_module.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive